name: Create Pull Request
on:
  workflow_dispatch:

jobs:
  create-pr:
    uses: actions/versions-package-tools/.github/workflows/create-pr-to-update-manifest.yml@main
    with:
      tool-name: "node"
    secrets: inherit
